name: Continuous Integration

# Define when CI workflow is run
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Docker image version'
        required: true
        default: '0.0.0'
      image_publish:
        description: 'Publish image'
        default: 'false' 
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  continuous_integration:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      ENV_VAR_PUBLISH: ${{ github.event.inputs.image_publish == '' && 'false' || github.event.inputs.image_publish }}
      ENV_VAR_VERSION: ${{ github.event.inputs.image_version == '' && '0.0.0' || github.event.inputs.image_version }}
    
    steps:
      - uses: actions/checkout@v3  
      
      - name: Dump environment variables
        shell: bash
        run: |
          echo "ENV_VAR_PUBLISH = ${{env.ENV_VAR_PUBLISH}}"
          echo "ENV_VAR_VERSION = ${{env.ENV_VAR_VERSION}}"
          
      - name: Build docker image
        run: docker build . --file Dockerfile --tag ghcr.io/tiagosarmentosantos/docker-clang-format:${{env.ENV_VAR_VERSION}}

      - name: Run docker image
        run: docker run --rm -v ${PWD}:/workdir --workdir /workdir ghcr.io/tiagosarmentosantos/docker-clang-format:${{env.ENV_VAR_VERSION}} --version
      
      # See reference here: https://github.com/jonashackt/docker-hello-world/blob/main/.github/workflows/publish.yml
      - if: ${{ env.ENV_VAR_PUBLISH == 'true' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - if: ${{ env.ENV_VAR_PUBLISH == 'true' }}
        name: Publish docker image
        run: docker push ghcr.io/tiagosarmentosantos/docker-clang-format:${{env.ENV_VAR_VERSION}}
