name: Continuous Integration

# Define when CI workflow is run
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Docker image version'
        required: true
        default: '0.0.0'
      publish_image:
        description: 'Publish image'
        default: 'false' 
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  continuous_integration:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup enviroment variables
        run: |
          echo "Input variable for image publish is: ${IN_VAR_PUBLISH}"   
          echo "Input variable for image version is: ${IN_VAR_VERSION}"
        env: |
          IN_VAR_PUBLISH: ${{ github.event.inputs.publish_image }}
          IN_VAR_VERSION: ${{ github.event.inputs.image_version }}

      # See reference here: https://github.com/jonashackt/docker-hello-world/blob/main/.github/workflows/publish.yml
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build docker image
        run: docker build . --file Dockerfile --tag ghcr.io/tiagosarmentosantos/docker-clang-format:${JOB_VAR_VERSION}

      - name: Run docker image
        run: docker run --rm -v ${PWD}:/workdir --workdir /workdir ghcr.io/tiagosarmentosantos/docker-clang-format:${JOB_VAR_VERSION} --version
        
      - if: ${{ github.event.inputs.publish_image == 'true' }}
        name: Publish docker image
        run: docker push ghcr.io/tiagosarmentosantos/docker-clang-format:${JOB_VAR_VERSION}
